nacos:
  config:
    bootstrap:
      enable: true
    server-addr: 127.0.0.1:8848
    remote-first: true
    data-ids: devilService,runningService
    namespace: runningwind
    group: DEFAULT_GROUP
    type: properties
    auto-refresh: true
    max-retry: 10
    config-retry-time: 2000
    config-long-poll-timeout: 10000
    enable-remote-sync-config: true
    username: nacos
    password: nacos
spring:
  application:
    name: devil-nacos
server:
  port: 9999