nacos:
  config:
    bootstrap:
      enable: true
    server-addr: 172.19.0.50:8848
    remote-first: true
    data-ids: nacos-example
    namespace: devil-namespace
    group: DEFAULT_GROUP
    type: yaml
    auto-refresh: true
    max-retry: 10
    config-retry-time: 2000
    config-long-poll-timeout: 10000
    enable-remote-sync-config: true
    username: nacos
    password: nacos
spring:
  application:
    name: nacos-example
server:
  port: 9999